## SINGLE model
library(scales)
## B&B model

rm(list=ls())
graphics.off()

# Parameters set corresponding to the first species in paramteter sets of the 2-species models
situation_names = c('iteroparous/delayed maturation', 'semelparous/fast maturation', 'semelparous/delayed maturation', 'iteroparous/fast maturation')
fert1<-30
phi1 <-0.5

matur1<-c(0.7,1,0.7,1)
s1a<-c(0.5,0,0,0.5)

alpha = 0.1
beta = 0.1


# Creating vectors
years <- 300
TimeVec<-seq(1,years+1)
N1j<-matrix(0,4,years+1)
N1a<-matrix(0,4,years+1)
svar1j<-matrix(0,4,years+1)
fvar1j<-matrix(0,4,years+1)

N1j_2<-matrix(0,4,years+1)
N1a_2<-matrix(0,4,years+1)

#4. INITIALIZATION
N0 <- 50
for(i in 1:4){
  N1j[i,1] <-N0
  N1a[i,1] <-N0
}

for (t in 1:years){
  for(i in 1:4){ 
    
    svar1j[i,t] <- phi1/(1+beta*N1a[i,t]) ## competition on juv surv generated by adults
    
    fvar1j[i,t] <- fert1/(1+alpha*N1a[i,t]) ## competition on fertility generated by adults
    
    N1j[i,t+1]<-(1-matur1[i])*svar1j[i,t]*N1j[i,t] + (fvar1j[i,t]*N1a[i,t]) 
    
    N1a[i,t+1]<-matur1[i]*svar1j[i,t]*N1j[i,t] + s1a[i]*N1a[i,t]
  }
}

#4. INITIALIZATION
N0 <- 50
for(i in 1:4){
  N1j_2[i,1] <-0
  N1a_2[i,1] <-N0
}

for (t in 1:years){
  for(i in 1:4){ 
    
    svar1j[i,t] <- phi1/(1+beta*N1a_2[i,t]) ## competition on juv surv generated by adults
    
    fvar1j[i,t] <- fert1/(1+alpha*N1a_2[i,t]) ## competition on fertility generated by adults
    
    N1j_2[i,t+1]<-(1-matur1[i])*svar1j[i,t]*N1j_2[i,t] + (fvar1j[i,t]*N1a_2[i,t]) 
    
    N1a_2[i,t+1]<-matur1[i]*svar1j[i,t]*N1j_2[i,t] + s1a[i]*N1a_2[i,t]
  }
}

pdf(file = "singlesp_adultDD_2cond_ini.pdf",height=8,width=8)
par(mfrow=c(2,2))
for(i in 1:4){  
  plot(TimeVec,N1j[i,]+N1a[i,] ,type="l",
       xlab='Time (years)',ylab='Population Density', cex.main = 1.2, 
       ylim=c(0, 1.2*max(N1j[i,]+N1a[i,])),cex.lab = 1.2,lty = 1, lwd = 1 , col='cyan')
  title(situation_names[i])
  lines(TimeVec,N1j_2[i,]+N1a_2[i,],lty = 1,lwd=1,col=alpha(rgb(0,0,0.9), 0.3))
  legend(150,50,legend=c(expression("n"['j']*"(0) = 50", "n"['j']*"(0) = 0")), col=c("cyan", alpha(rgb(0,0,0.9), 0.3)), lty=1, cex=0.7)
}
dev.off()


##### M&B model

# Creating vectors
years <- 300
TimeVec<-seq(1,years+1)
N1j<-matrix(0,4,years+1)
N1a<-matrix(0,4,years+1)
svar1j<-matrix(0,4,years+1)
fvar1j<-matrix(0,4,years+1)
N1j_2<-matrix(0,4,years+1)
N1a_2<-matrix(0,4,years+1)

#4. INITIALIZATION
N0 <- 50
for(i in 1:4){
  N1j[i,1] <-N0
  N1a[i,1] <-N0
}

for (t in 1:years){
  for(i in 1:4){ 
    
    svar1j[i,t] <- phi1/(1+beta*N1j[i,t]) ## competition on juv surv generated by juveniles
    
    fvar1j[i,t] <- fert1/(1+alpha*N1a[i,t]) ## competition on fertility generated by adults
    
    N1j[i,t+1]<-(1-matur1[i])*svar1j[i,t]*N1j[i,t] + (fvar1j[i,t]*N1a[i,t]) 
    
    N1a[i,t+1]<-matur1[i]*svar1j[i,t]*N1j[i,t] + s1a[i]*N1a[i,t]
  }
}

N0 <- 50
for(i in 1:4){
  N1j_2[i,1] <-0
  N1a_2[i,1] <-N0
}

for (t in 1:years){
  for(i in 1:4){ 
    
    svar1j[i,t] <- phi1/(1+beta*N1a_2[i,t]) ## competition on juv surv generated by adults
    
    fvar1j[i,t] <- fert1/(1+alpha*N1a_2[i,t]) ## competition on fertility generated by adults
    
    N1j_2[i,t+1]<-(1-matur1[i])*svar1j[i,t]*N1j_2[i,t] + (fvar1j[i,t]*N1a_2[i,t]) 
    
    N1a_2[i,t+1]<-matur1[i]*svar1j[i,t]*N1j_2[i,t] + s1a[i]*N1a_2[i,t]
  }
}


pdf(file = "singlesp_metamorph_2cond_ini.pdf",height=8,width=8)
par(mfrow=c(2,2))
for(i in 1:4){  
  plot(TimeVec,N1j[i,]+N1a[i,] ,type="l",
       xlab='Time (years)',ylab='Population Density', cex.main = 1.2, 
       ylim=c(0, 1.2*max(N1j[i,]+N1a[i,])),cex.lab = 1.2,lty = 1, lwd = 1 , col='cyan')
  title(situation_names[i])
  lines(TimeVec,N1j_2[i,]+N1a_2[i,],lty = 1,lwd=1,col=alpha(rgb(0,0,0.9), 0.3))
  legend(150,50,legend=c(expression("n"['j']*"(0) = 50", "n"['j']*"(0) = 0")), col=c("cyan", alpha(rgb(0,0,0.9), 0.3)), lty=1, cex=0.7)
}
dev.off()

