## SINGLE model

## B&B model

rm(list=ls())
graphics.off()

# Parameters set corresponding to the first species in paramteter sets of the 2-species models
situation_names = c('classic', 'semelparous/immediate maturation', 'semelparous/delayed maturation', 'iteroparous/immediate maturation')
fert1<-300
phi1 <-0.85

matur1<-c(0.7,1,0.7,1)
s1a<-c(0.5,0,0,0.5)

alpha = 0.1
beta = 0.1


# Creating vectors
years <- 3000
TimeVec<-seq(1,years+1)
N1j<-matrix(0,4,years+1)
N1a<-matrix(0,4,years+1)
svar1j<-matrix(0,4,years+1)
fvar1j<-matrix(0,4,years+1)


#4. INITIALIZATION
N0 <- 50
for(i in 1:4){
  N1j[i,1] <-N0
  N1a[i,1] <-N0
}

for (t in 1:years){
  for(i in 1:4){ 
    
    svar1j[i,t] <- phi1/(1+beta*N1a[i,t]) ## competition on juv surv generated by adults
    
    fvar1j[i,t] <- fert1/(1+alpha*N1a[i,t]) ## competition on fertility generated by adults

    N1j[i,t+1]<-(1-matur1[i])*svar1j[i,t]*N1j[i,t] + (fvar1j[i,t]*N1a[i,t]) 

    N1a[i,t+1]<-matur1[i]*svar1j[i,t]*N1j[i,t] + s1a[i]*N1a[i,t]
  }
}

pdf(file = "singlesp_adultDD.pdf",height=8,width=8)
par(mfrow=c(2,2))
for(i in 1:4){  
  plot(TimeVec,N1j[i,]+N1a[i,] ,type="l",
       xlab='Time (years)',ylab='Population Density', cex.main = 1.2, 
       ylim=c(0, 1.2*max(N1j[i,]+N1a[i,])),cex.lab = 1.2,lty = 2, lwd = 2 , col='cyan')
  title(situation_names[i])
  # lines(TimeVec,N1a[i,],lty = 2,lwd=2,col='orange')
}
dev.off()

print(N1j[2,280:290]+N1a[2,280:290])

##### M&B model

# Creating vectors
TimeVec<-seq(1,years+1)
N1j<-matrix(0,4,years+1)
N1a<-matrix(0,4,years+1)
svar1j<-matrix(0,4,years+1)
fvar1j<-matrix(0,4,years+1)


#4. INITIALIZATION
N0 <- 50
for(i in 1:4){
  N1j[i,1] <-N0
  N1a[i,1] <-N0
}

for (t in 1:years){
  for(i in 1:4){ 
    
    svar1j[i,t] <- phi1/(1+beta*N1j[i,t]) ## competition on juv surv generated by juveniles
    
    fvar1j[i,t] <- fert1/(1+alpha*N1a[i,t]) ## competition on fertility generated by adults
    
    N1j[i,t+1]<-(1-matur1[i])*svar1j[i,t]*N1j[i,t] + (fvar1j[i,t]*N1a[i,t]) 
    
    N1a[i,t+1]<-matur1[i]*svar1j[i,t]*N1j[i,t] + s1a[i]*N1a[i,t]
  }
}

pdf(file = "singlesp_metamorph.pdf",height=8,width=8)
par(mfrow=c(2,2))
for(i in 1:4){  
  plot(TimeVec,N1j[i,]+N1a[i,] ,type="l",
       xlab='Time (years)',ylab='Population Density', cex.main = 1.2, 
       ylim=c(0, 1.2*max(N1j[i,]+N1a[i,])),cex.lab = 1.2,lty = 2, lwd = 2 , col='cyan')
  title(situation_names[i])
  # lines(TimeVec,N1a[i,],lty = 2,lwd=2,col='orange')
}
dev.off()

print(N1j[2,280:290]+N1a[2,280:290])